### ISSUE TITLE
`-newline` repeats the `$` part twice?

### ISSUE THREAD

**Issue by klauern** [justjanne/powerline-go#27] opened 2017-09-09 14:38 UTC
This looks like an issue with my prompt, but when I added the `-newline` option, it repeats the `$` on both lines:

![image](https://user-images.githubusercontent.com/4735/30241086-80037ca8-9542-11e7-8cca-2009e4cafc91.png)

```sh
PS1="$(~/bin/powerline-go -modules "time,cwd,perms,git,jobs,exit,root" -error $? -newline)"
```

**Comment by justjanne** [comment] 2017-09-14 06:48
Duplicate of Issue #10

**Closed by justjanne** 2017-09-14 06:48 UTC
