### ISSUE TITLE
Weird extra spaces at the end of the path.

### ISSUE THREAD

**Issue by eteran** [justjanne/powerline-go#205] opened 2020-06-10 21:16 UTC
First of all, thank you for this port of powerline! It's great, easy to configure and doesn't break when I update my system python install ;-)

So I've noticed a weird issue where I get extra whitespace at the end of the prompt. It is more pronounced when I SSH into the box

It seems proportional to the number of directories are in my CWD path. (I get 2 spaces when in `/`, but for some longer paths I see 3 or 4 spaces). Or perhaps it's tied to the number of segments being displayed?

I'll some screenshots to show you what I mean.

![image](https://user-images.githubusercontent.com/571477/84319161-9175e980-ab3d-11ea-8b16-f7cc4cfab667.png)

This is as far left as the command text will let me delete to! As you can see, there are 2 spaces after the prompt, 1 seems to be more desirable):

![image](https://user-images.githubusercontent.com/571477/84319240-b4a09900-ab3d-11ea-9cec-2eb5a4b63b45.png)

Now, if I `cd` into a longer directory, I get 3 spaces after the prompt!

![image](https://user-images.githubusercontent.com/571477/84319334-dc8ffc80-ab3d-11ea-9b0b-2c885a4acb41.png)

With a long enough path, I can get it up to 4 or 5 spaces. In case it matters, here is the relevant portions of my `.bashrc`

```
GOPATH=$HOME/go

function _update_ps1() {
    PS1="$($GOPATH/bin/powerline-go -alternate-ssh-icon -hostname-only-if-ssh)"
}

if [ "$TERM" != "linux" ] && [ -f "$GOPATH/bin/powerline-go" ]; then
    PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi
```

**Comment by andrzejnovak** [comment] 2020-06-11 14:07
Seeing this as well

**Comment by KMaheshBhat** [comment] 2020-06-11 18:48
I too am seeing this on Windows 10 + Git Bash.

**Comment by justjanne** [comment] 2020-06-20 11:37
It’s an issue with the east-asian-runes fix, caused by go-runewidth being inaccurate :(

**Comment by Lyrillind** [comment] 2020-06-24 02:00
Same on macOS + iTerms2

**Comment by tuomastielinen** [comment] 2020-06-24 12:33
Same with WSL and Windows Terminal.

**Comment by rezonanc** [comment] 2020-08-20 19:48
> It’s an issue with the east-asian-runes fix, caused by go-runewidth being inaccurate :(

Is it somehow possible to revert the fix? Maybe you could point us to a direction where we could make this change locally? Besides this weird space at the end the project seems to be awesome!

**Comment by sql-sith** [comment] 2020-09-12 19:31
I can plus-one this on WSL Ubuntu.

I can also plus-ten your project. I have tried, and given up, on a few other powerline projects for bash because of various reasons, one of which is that I'm really busy at work right now and the documentation did not make it easy enough for me to implement them quickly and successfully. This project and its documentation, however, are awesome. Thank you so much for building and maintaining powerline-go.

**Comment by mschneider82** [comment] 2020-09-17 11:29
i fixed it with a workaround, replace the last line in main.go with 

```
	fmt.Print(strings.TrimRight(p.draw(), " ") + " ")
```

this i dirty way but solves this problem.

**Comment by eteran** [comment] 2020-09-29 01:05
@mschneider82 works great. Perhaps if you want the PR to be accepted then it should either trim right or left, depending on if the prompt is left or right-aligned?

That's what I'd probably want if I was the author.

**Comment by justjanne** [comment] 2021-01-06 16:17
This should be fixed now, please re-open if it occurs again

**Closed by justjanne** 2021-01-06 16:17 UTC
