### ISSUE TITLE
feature request: xonsh support

### ISSUE THREAD

**Issue by OneOfOne** [justjanne/powerline-go#24] opened 2017-08-31 20:28 UTC
any chance to support xonsh?

**Comment by justjanne** [comment] 2017-09-01 11:46
Have you tried configuring it for bash, with -shell bare as additional parameter? xonsh should (according to its documentation) find and use it automatically then.

**Comment by justjanne** [comment] 2017-10-19 10:47
As I can't reproduce the issue, I'll close this if no further information is provided until Oct 31st

**Closed** 2019-12-12 13:54 UTC
Labels: enhancement, waiting on response
